In [35]:
from xgboost import XGBClassifier
import xgboost as xgb
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
results = pd.DataFrame(columns=['model', 'accuracy', 'precision', 'recall', 'f1', 'conf_matrix']).dropna()
from sklearn.metrics import accuracy_score, precision_score
from sklearn.metrics import recall_score, f1_score, confusion_matrix, roc_curve, auc, precision_recall_curve


def appendError(model, testy, y_pred):
    accuracy = accuracy_score(testy, y_pred)
    precision = precision_score(testy, y_pred)
    recall = recall_score(testy, y_pred)
    f1 = f1_score(testy, y_pred)
    conf_matrix = confusion_matrix(testy, y_pred)
    return pd.DataFrame([{
        'model': model,
        'accuracy': accuracy,
        'precision': precision, 
        'recall': recall, 
        'f1': f1, 
        'conf_matrix': conf_matrix, 
    }])

In [5]:
data = pd.read_csv("set.csv").dropna()
data

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.080795,204.890456,20791.31898,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.05786,6.635246,333.775777,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.54173,9.275884,333.775777,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.41744,8.059332,356.886136,363.266516,18.436525,100.341674,4.628771,0
4,9.092223,181.101509,17978.98634,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
...,...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681736,47580.99160,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1
3272,7.808856,193.553212,17329.80216,8.061362,333.775777,392.449580,19.903225,66.396293,2.798243,1
3273,9.419510,175.762646,33155.57822,7.350233,333.775777,432.044783,11.039070,69.845400,3.298875,1
3274,5.126763,230.603758,11983.86938,6.303357,333.775777,402.883113,11.168946,77.488213,4.708658,1
3275,7.874671,195.102299,17404.17706,7.509306,333.775777,327.459761,16.140368,78.698446,2.309149,1

In [15]:
X = data.drop(columns=['Potability'])
y = data['Potability']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [29]:
bst = XGBClassifier(n_estimators=20, max_depth=3, learning_rate=10, objective='binary:logistic')
bst.fit(X_train, y_train)
preds = bst.predict(X_test)
results = pd.concat([results, appendError("xgb ns", y_test, preds)])

In [30]:
results

    model  accuracy  precision    recall        f1              conf_matrix
0  xgb ns  0.646341   0.588517  0.457249  0.514644  [[301, 86], [146, 123]]
0  xgb ns  0.621951   0.705882  0.133829  0.225000   [[372, 15], [233, 36]]
0  xgb ns  0.589939   0.000000  0.000000  0.000000     [[387, 0], [269, 0]]
0  xgb ns  0.589939   0.500000  0.003717  0.007380     [[386, 1], [268, 1]]
0  xgb ns  0.394817   0.389655  0.840149  0.532391   [[33, 354], [43, 226]]
0  xgb ns  0.589939   0.500000  0.003717  0.007380     [[386, 1], [268, 1]]

In [31]:
scaler = StandardScaler()
Xs = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=.2)

In [46]:
bst = XGBClassifier()
bst.fit(X_train, y_train)
preds = bst.predict(X_test)
print(classification_report(y_test, preds))
print(confusion_matrix(y_test, preds))

              precision    recall  f1-score   support

           0       0.66      0.80      0.73       391
           1       0.58      0.40      0.47       265

    accuracy                           0.64       656
   macro avg       0.62      0.60      0.60       656
weighted avg       0.63      0.64      0.62       656

[[313  78]
 [159 106]]

In [65]:
X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=.2)
specs = ["dart", "hist", 5, 3, 'gradient_based']
bst = XGBClassifier(booster=specs[0], tree_method=specs[1], max_depth=specs[2], gamma=specs[3])
bst.fit(X_train, y_train)
preds = bst.predict(X_test)
print(classification_report(y_test, preds))
print(confusion_matrix(y_test, preds))

              precision    recall  f1-score   support

           0       0.69      0.93      0.79       409
           1       0.73      0.30      0.42       247

    accuracy                           0.69       656
   macro avg       0.71      0.62      0.61       656
weighted avg       0.70      0.69      0.65       656

[[381  28]
 [173  74]]

In [70]:
specs = ["dart", "hist", 5, 3, 'gradient_based']
bst = XGBClassifier(booster=specs[0], tree_method=specs[1], max_depth=specs[2], gamma=specs[3])
bst.fit(X_train, y_train)
preds = bst.predict(X_test)
print(classification_report(y_test, preds))
print(confusion_matrix(y_test, preds))

              precision    recall  f1-score   support

           0       0.69      0.93      0.79       409
           1       0.73      0.30      0.42       247

    accuracy                           0.69       656
   macro avg       0.71      0.62      0.61       656
weighted avg       0.70      0.69      0.65       656

[[381  28]
 [173  74]]

In [71]:
bst.save_model("69.json")